---
apiVersion: v1
kind: Service
metadata:
  name: tinyestate-db-service
  labels:
    app: tinyestate-db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: tinyestate-db-db-port
  selector:
    app: tinyestate-db
